// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUqSIsuWvDi1a9vojOyyr83aTkUQp53vM',
    appId: '1:784380872372:web:67b18dd70f3dc5e30439e1',
    messagingSenderId: '784380872372',
    projectId: 'study-buddy-400416',
    authDomain: 'study-buddy-400416.firebaseapp.com',
    databaseURL: 'https://study-buddy-400416-default-rtdb.firebaseio.com',
    storageBucket: 'study-buddy-400416.appspot.com',
    measurementId: 'G-YLNNNJP37D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45vHofSnh_BF4FlIKaGAkkLkVg2tgRcY',
    appId: '1:784380872372:android:572bc012f4be10950439e1',
    messagingSenderId: '784380872372',
    projectId: 'study-buddy-400416',
    databaseURL: 'https://study-buddy-400416-default-rtdb.firebaseio.com',
    storageBucket: 'study-buddy-400416.appspot.com',
  );
}
